# Generated by Django 2.1.3 on 2018-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_rule', models.CharField(max_length=500, unique=True)),
                ('provider', models.CharField(choices=[('RUSSIAN_POST', 'RUSSIAN_POST'), ('SDEK', 'SDEK'), ('PICKUP', 'PICKUP')], max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='SdekCity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fias', models.UUIDField()),
                ('kladr', models.CharField(max_length=16)),
                ('pvz_code', models.CharField(max_length=8)),
            ],
        ),
    ]
