# Generated by Django 2.1.3 on 2018-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='parse_rule',
            field=models.CharField(max_length=500, unique=True, verbose_name='Строка из Тильды'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='provider',
            field=models.CharField(choices=[('RUSSIAN_POST', 'RUSSIAN_POST'), ('SDEK', 'SDEK'), ('PICKUP', 'PICKUP')], max_length=32, verbose_name='служба'),
        ),
    ]
