# Generated by Django 2.1.3 on 2018-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('geometry', models.CharField(choices=[('BOX', 'BOX'), ('TUBE', 'TUBE')], max_length=32)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
            },
        ),
    ]
