# Generated by Django 2.1.3 on 2018-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
