# Generated by Django 2.1.3 on 2018-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_equipment_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'упаковка', 'verbose_name_plural': 'упаковки'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='geometry',
            field=models.CharField(choices=[('BOX', 'BOX'), ('TUBE', 'TUBE')], max_length=32, verbose_name='геометрия'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='height',
            field=models.IntegerField(verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='length',
            field=models.IntegerField(verbose_name='длина'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weight',
            field=models.IntegerField(verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='width',
            field=models.IntegerField(verbose_name='ширина'),
        ),
    ]
