# Generated by Django 2.1.3 on 2018-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20181206_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'equipment', 'verbose_name_plural': 'equipments'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='geometry',
            field=models.CharField(choices=[('BOX', 'BOX'), ('TUBE', 'TUBE')], max_length=32, verbose_name='geometry'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='height',
            field=models.IntegerField(verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='length',
            field=models.IntegerField(verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weight',
            field=models.IntegerField(verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='width',
            field=models.IntegerField(verbose_name='width'),
        ),
    ]
