# Generated by Django 2.1.3 on 2018-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('sku', models.CharField(help_text='sku.help_text', max_length=255, primary_key=True, serialize=False, verbose_name='sku')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('geometry', models.CharField(choices=[('BOX', 'BOX'), ('TUBE', 'TUBE')], default='BOX', max_length=16, verbose_name='geometry')),
                ('width', models.IntegerField(verbose_name='width')),
                ('height', models.IntegerField(verbose_name='height')),
                ('length', models.IntegerField(verbose_name='length')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('weight', models.IntegerField(verbose_name='weight')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
