version: '3'
services:

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: pplanner
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - "db_admin:/var/lib/pgadmin"
    ports:
    - "5050:80"

  mongodb:
    image: mongo
    restart: always
    volumes:
      - "mongodb:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pplanner
    command: "mongod --auth --smallfiles --bind_ip=0.0.0.0"

  mongodb-ui:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: pplanner
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pplanner

  rabbit:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - "15672:15672"
    volumes:
      - "rabbit:/var/lib/rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: pplanner
      RABBITMQ_DEFAULT_VHOST: pplanner

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always
    environment:
      LOG_LEVEL: DEBUG
      LOG_FILE: /var/log/gunicorn.log
      MONGODB_URL: mongodb://root:pplanner@mongodb:27017/pplanner?authSource=admin
      DATABASE_URL: psql://developer:developer@db:5432/pplanner

  app:
    build: .
    restart: always
    environment:
      LOG_LEVEL: DEBUG
      LOG_FILE: /var/log/gunicorn.log
      MONGODB_URL: mongodb://root:pplanner@mongodb:27017/pplanner?authSource=admin
      DATABASE_URL: psql://developer:developer@db:5432/pplanner
    ports:
      - "80:80"

volumes:
  db: {}
  db_admin: {}
  mongodb: {}
  rabbit: {}
