FROM registry.gitlab.com/mypplanner/docker-django

ENV PYTHONUNBUFFERED 1

ARG src=/usr/src/app

WORKDIR $src

ADD . .

RUN ./manage.py collectstatic --no-input
RUN ./manage.py compilemessages

CMD ["celery", "-A", "config", "worker", "-l", "info"]
