# Generated by Django 2.1.3 on 2018-11-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('delivery', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=511)),
                ('phone', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=255)),
                ('comment', models.TextField()),
                ('is_payed', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=512, null=True)),
                ('result', models.CharField(blank=True, max_length=511, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('region_fias_id', models.UUIDField(blank=True, null=True)),
                ('region_type', models.CharField(blank=True, max_length=5, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('area_fias_id', models.UUIDField(blank=True, null=True)),
                ('area_type', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('city_fias_id', models.UUIDField(blank=True, null=True)),
                ('city_type', models.CharField(blank=True, max_length=5, null=True)),
                ('city_district', models.CharField(blank=True, max_length=255, null=True)),
                ('city_district_fias_id', models.UUIDField(blank=True, null=True)),
                ('city_district_type', models.CharField(blank=True, max_length=5, null=True)),
                ('settlement', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_fias_id', models.UUIDField(blank=True, null=True)),
                ('settlement_type', models.CharField(blank=True, max_length=5, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_fias_id', models.UUIDField(blank=True, null=True)),
                ('street_type', models.CharField(blank=True, max_length=5, null=True)),
                ('house', models.CharField(blank=True, max_length=255, null=True)),
                ('house_fias_id', models.UUIDField(blank=True, null=True)),
                ('house_type', models.CharField(blank=True, max_length=5, null=True)),
                ('block', models.CharField(blank=True, max_length=64, null=True)),
                ('block_type', models.CharField(blank=True, max_length=5, null=True)),
                ('flat', models.CharField(blank=True, max_length=64, null=True)),
                ('flat_type', models.CharField(blank=True, max_length=5, null=True)),
                ('geo_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geo_lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='OrderArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.Article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
            options={
                'verbose_name': 'order_article',
                'verbose_name_plural': 'order_articles',
            },
        ),
        migrations.CreateModel(
            name='OrderEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Equipment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order')),
            ],
            options={
                'verbose_name': 'order_equipment',
                'verbose_name_plural': 'order_equipments',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.OrderAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Delivery'),
        ),
    ]
