# Generated by Django 2.1.3 on 2018-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181119_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='unparsed_parts',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
