# Generated by Django 2.1.3 on 2018-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
