# Generated by Django 2.1.3 on 2018-12-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181204_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.OrderAddress', verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Delivery', verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=511, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.IntegerField(default=0, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='оплачен ли заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length',
            field=models.IntegerField(default=0, verbose_name='длина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=15, verbose_name='номер платежа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='система оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=31, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='сумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='трек-номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.IntegerField(default=0, verbose_name='ширина'),
        ),
    ]
