# Generated by Django 2.1.3 on 2018-12-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20181206_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.OrderAddress', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Delivery', verbose_name='delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=511, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.IntegerField(default=0, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='is_payed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length',
            field=models.IntegerField(default=0, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='middle_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='payment_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='payment_system'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=31, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='promo_code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='track'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.IntegerField(default=0, verbose_name='width'),
        ),
    ]
