# Generated by Django 2.1.3 on 2018-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20181206_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amo_order_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
